const ENDPOINTS = {
  STUDENTS: "/students",
  STUDENT_DETAILS: "/students/details",
  BATCHES: "/batches",
  ENROLLMENTS: "/enrollments",
  INSTITUTE_BRANCHES: "/institute-branches",
  ACADEMIC_BRANCHES: "/academic-branches",
  BUSES: "/buses",
  CITIES: "/cities",
  STUDENT_STATUSES: "/student-statuses",
  ACADEMIC_RECORDS: "/academic-records",
  CONTACTS: "/contact-details",
  STUDENT_SUMMARY: "/contact-details/student",
  EMPLOYEES: "/employees",
  SUBJECTS: "/subjects",
  TEACHERS: "/teachers",
  KNOW_WAYS: "/knowledge-sources",
  CLASS_ROOMS: "/class-rooms",
  ATTENDANCE: "/attendance",
  SCHOOLS: "/schools",
  GUARDIANS: "/guardians",
  FAMILIES: "/families",

  PAYMENTS: "/payments",
  PAYMENTS_LATEST_PER_STUDENT: "/payments/latest-per-student",
  PAYMENTS_STUDENT_LATE: "/payments/student-late",
  ENROLLMENTS: "/enrollments",
  BATCH_STUDENTS: "/batch-students",
  BATCH_STUDENT_SUBJECTS: "/batch-student-subjects",
  MESSAGE_TEMPLATES: "/message-templates",
  NOTIFICATIONS: "/notifications",
};

export default ENDPOINTS;
