/**
 * Mock data for Report Pages
 */

export const branches = [
  { id: 1, name: "فرع المزة" },
  { id: 2, name: "فرع كفرسوسة" },
  { id: 3, name: "فرع الشعلان" },
  { id: 4, name: "فرع الميدان" },
];

export const departments = [
  { id: 1, name: "قسم المحاسبة" },
  { id: 2, name: "قسم تقنية المعلومات" },
  { id: 3, name: "قسم الموارد البشرية" },
  { id: 4, name: "الهيئة التدريسية" },
];

export const employees = [
  { id: 1, name: "أحمد المحمد", branchId: 1, deptId: 4 },
  { id: 2, name: "سارة العلي", branchId: 1, deptId: 1 },
  { id: 3, name: "محمد خالد", branchId: 2, deptId: 2 },
  { id: 4, name: "ليلى حسن", branchId: 3, deptId: 3 },
  { id: 5, name: "ياسين عمر", branchId: 2, deptId: 4 },
  { id: 6, name: "رنا يوسف", branchId: 4, deptId: 4 },
  { id: 7, name: "خالد منصور", branchId: 1, deptId: 2 },
  { id: 8, name: "منى سعيد", branchId: 3, deptId: 1 },
];

export const monthlyReportsData = [
  {
    id: 1,
    employeeName: "أحمد المحمد",
    branch: "فرع المزة",
    branchId: 1,
    department: "الهيئة التدريسية",
    month: "مارس 2024",
    attendanceDays: 22,
    absenceDays: 2,
    delayCount: 3,
    overtimeHours: 5,
    status: "completed",
  },
  {
    id: 2,
    employeeName: "سارة العلي",
    branch: "فرع المزة",
    branchId: 1,
    department: "قسم المحاسبة",
    month: "مارس 2024",
    attendanceDays: 24,
    absenceDays: 0,
    delayCount: 0,
    overtimeHours: 2,
    status: "completed",
  },
  {
    id: 3,
    employeeName: "محمد خالد",
    branch: "فرع كفرسوسة",
    branchId: 2,
    department: "قسم تقنية المعلومات",
    month: "مارس 2024",
    attendanceDays: 20,
    absenceDays: 4,
    delayCount: 5,
    overtimeHours: 0,
    status: "pending",
  },
  {
    id: 4,
    employeeName: "ليلى حسن",
    branch: "فرع الشعلان",
    branchId: 3,
    department: "قسم الموارد البشرية",
    month: "مارس 2024",
    attendanceDays: 21,
    absenceDays: 3,
    delayCount: 1,
    overtimeHours: 8,
    status: "completed",
  },
  {
    id: 5,
    employeeName: "ياسين عمر",
    branch: "فرع كفرسوسة",
    branchId: 2,
    department: "الهيئة التدريسية",
    month: "مارس 2024",
    attendanceDays: 23,
    absenceDays: 1,
    delayCount: 2,
    overtimeHours: 4,
    status: "completed",
  },
];

export const attendanceReportsData = [
  {
    id: 1,
    employeeName: "أحمد المحمد",
    branch: "فرع المزة",
    branchId: 1,
    department: "الهيئة التدريسية",
    date: "2024-03-20",
    checkIn: "08:05 AM",
    checkOut: "04:30 PM",
    status: "present",
    delayMinutes: 5,
    notes: "-",
  },
  {
    id: 2,
    employeeName: "سارة العلي",
    branch: "فرع المزة",
    branchId: 1,
    department: "قسم المحاسبة",
    date: "2024-03-20",
    checkIn: "07:55 AM",
    checkOut: "04:00 PM",
    status: "present",
    delayMinutes: 0,
    notes: "حضور مبكر",
  },
  {
    id: 3,
    employeeName: "محمد خالد",
    branch: "فرع كفرسوسة",
    branchId: 2,
    department: "قسم تقنية المعلومات",
    date: "2024-03-20",
    checkIn: "-",
    checkOut: "-",
    status: "absent",
    delayMinutes: 0,
    notes: "إجازة مرضية",
  },
  {
    id: 4,
    employeeName: "ليلى حسن",
    branch: "فرع الشعلان",
    branchId: 3,
    department: "قسم الموارد البشرية",
    date: "2024-03-20",
    checkIn: "08:45 AM",
    checkOut: "04:15 PM",
    status: "late",
    delayMinutes: 45,
    notes: "-",
  },
  {
    id: 5,
    employeeName: "ياسين عمر",
    branch: "فرع كفرسوسة",
    branchId: 2,
    department: "الهيئة التدريسية",
    date: "2024-03-20",
    checkIn: "08:10 AM",
    checkOut: "04:05 PM",
    status: "present",
    delayMinutes: 10,
    notes: "-",
  },
  {
    id: 6,
    employeeName: "رنا يوسف",
    branch: "فرع الميدان",
    branchId: 4,
    department: "الهيئة التدريسية",
    date: "2024-03-20",
    checkIn: "-",
    checkOut: "-",
    status: "on-leave",
    delayMinutes: 0,
    notes: "إجازة سنوية",
  },
];
